{% set name = "myhdl" %}
{% set version = "0.11.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 814cf7872c816a7fb8abe96d98b243b815da9e898056dfdbbdb68063daee6496

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - myhdl

about:
  home: http://www.myhdl.org
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python as a Hardware Description Language
  doc_url: http://docs.myhdl.org/
  dev_url: https://github.com/myhdl/myhdl

extra:
  recipe-maintainers:
    - davidbrochart
